selected_episodes:
    - coke_tray/000
    - coke_tray/001
    - coke_tray/002
    - coke_tray/003
    - coke_tray/004
    - sponge_tray/000
    - sponge_tray/001
    - sponge_tray/002
    - sponge_tray/003
    - sponge_tray/004
    - drawer/000
    - drawer/001
    - drawer/002
    - drawer/003
    - drawer/004
    - adrian_cabinet/000
    - adrian_cabinet/001
    - adrian_cabinet/002
    - adrian_cabinet/003
    - adrian_cabinet/004
    - hanoi_tower_3/000
    - hanoi_tower_3/001
    - hanoi_tower_3/002
    - hanoi_tower_3/003
    - hanoi_tower_3/004
    - plugging_phone_charger/001
    - plugging_phone_charger/002
    - plugging_phone_charger/004
    - pour_ttballs_cup_gray_bowl/000
    - pour_ttballs_cup_gray_bowl/001
    - pour_ttballs_cup_gray_bowl/003
    - pour_ttballs_cup_gray_bowl/004
    - paperroll_upright/000
    - paperroll_upright/001
    - paperroll_upright/002
    - paperroll_upright/003
    - paperroll_upright/004
    - tennisball_cup_laying/000
    - tennisball_cup_laying/001
    - tennisball_cup_laying/002
    - tennisball_cup_upright/003
    - tennisball_cup_upright/004
    - cleanup_box/000
    - cleanup_box/001
    - cleanup_box/003
    - cleanup_box/004
    - cleanup_box/005
backup_episodes:
    - coke_tray/005
    - sponge_tray/005
    - drawer/005
    - adrian_cabinet/005
    - hanoi_tower_3/005
